// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const importMetaEnv = typeof import.meta !== 'undefined'
  ? ((import.meta as unknown as { env?: Record<string, string | undefined> }).env ?? undefined)
  : undefined;

const resolveImportMetaEnv = (): EnvSource | undefined => {
  try {
    return (import.meta as ImportMeta & { env?: EnvSource }).env;
  } catch {
    return undefined;
  }
};

const SUPABASE_URL = envSource.VITE_SUPABASE_URL ?? 'http://localhost:54321';
const SUPABASE_PUBLISHABLE_KEY = envSource.VITE_SUPABASE_PUBLISHABLE_KEY ?? 'test-key';

const authStorage = typeof window !== 'undefined' && window?.localStorage ? window.localStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
